Vagrant.configure("2") do |config|
    # Configuration for Ubuntu 20.04
    config.vm.define "ubuntu" do |ubuntu|
      ubuntu.vm.box = "ubuntu/focal64"
      ubuntu.vm.network "private_network", ip: "192.168.17.100"
      ubuntu.vm.hostname = "gitlab.elroydevops.tech"
      ubuntu.vm.provider "virtualbox" do |vb|
        vb.memory = "1024" # Adjust as needed
        vb.cpus = 1        # Adjust as needed
      end
    end
  
    # Configuration for CentOS 7
    config.vm.define "centos" do |centos|
      centos.vm.box = "centos/7"
      centos.vm.network "private_network", ip: "192.168.17.102"
      centos.vm.hostname = "zabbix.elroydevops.tech"
      centos.vm.provider "virtualbox" do |vb|
        vb.memory = "4096" # Adjust as needed
        vb.cpus = 2        # Adjust as needed
      end
    end
  end
  