version: '3.1'

services:
  jenkins:
    restart: always
    build:
      context: . 
    image: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - var/jenkins_home:/var/jenkins_home
    container_name: jenkins
