version: '3.1'

services:
  jenkins:
    restart: always
    build:
      context: . 
    image: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
    container_name: jenkins

volumes:
  jenkins_data:
    name: my_jenkins_volume
