# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080